{% set name = "SourceXtractor" %}
{% set version = "0.22" %}
{% set build_number = 0 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: "0.22"
    git_url: https://github.com/astrorama/sourcextractorplusplus.git

build:
    number: {{ build_number }}

test:
    commands:
        - $PREFIX/bin/sourcextractor++ --version

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cython                             # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - python
        - boost
        - alexandria ==2.31.0
        - cfitsio >=3.470
        - CCfits >=2.5
        - wcslib >=7.3
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        - onnxruntime-cpp >=1.15
        - ncurses >=6.3
        - readline >=8
        - re2 >=2022.04.01
    run:
        - {{ pin_compatible('python', max_pin='x.x') }}
        - {{ pin_compatible('boost', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio', max_pin='x.x') }}
        - {{ pin_compatible('CCfits', max_pin='x.x') }}
        - {{ pin_compatible('wcslib', max_pin='x.x') }}
        - {{ pin_compatible('fftw', max_pin='x.x') }}
        - {{ pin_compatible('levmar', max_pin='x.x') }}
        - {{ pin_compatible('gsl', max_pin='x.x') }}
        - {{ pin_compatible('onnxruntime-cpp', max_pin='x.x') }}
        - {{ pin_compatible('ncurses', max_pin='x.x') }}
        - {{ pin_compatible('re2', max_pin='x.x.x') }}
        - astropy

app:
    entry: sourcextractor_launch.sh
    icon: sourcextractor_64.png
    summary: The next generation Source Extractor
    description: The next generation Source Extractor

about:
    home: https://github.com/astrorama/sourcextractorplusplus
    license: LGPLv3+
    license_file: LICENSE
    summary: The next generation Source Extractor

