{% set name = "SourceXtractor" %}
{% set version = "0.19.2" %}
{% set build_number = 3 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: "0.19.2"
    git_url: https://github.com/astrorama/sourcextractorplusplus.git

build:
    number: {{ build_number }}

test:
    commands:
        - $PREFIX/bin/sourcextractor++ --version

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cython                             # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - python
        - boost
        - alexandria ==2.28.2
        - cfitsio >=3.470
        - CCfits >=2.5
        - wcslib >=7.3
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        - onnxruntime-cpp ==1.12
        - ncurses ==6.2
        - readline ==8
        - re2
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio') }}
        - {{ pin_compatible('CCfits') }}
        - {{ pin_compatible('wcslib') }}
        - {{ pin_compatible('fftw') }}
        - {{ pin_compatible('levmar') }}
        - {{ pin_compatible('gsl') }}
        - {{ pin_compatible('onnxruntime-cpp', min_pin='x.x.x', max_pin='x.x.x') }}
        - {{ pin_compatible('ncurses') }}
        - astropy

app:
    entry: sourcextractor_launch.sh
    icon: sourcextractor_64.png
    summary: The next generation Source Extractor
    description: The next generation Source Extractor

about:
    home: https://github.com/astrorama/sourcextractorplusplus
    license: LGPLv3+
    license_file: LICENSE
    summary: The next generation Source Extractor

